/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MetodoSecante;

/**
 * @author isaac
 */
//importar bigdeciamles


import javax.swing.table.DefaultTableModel;

public class Secantes extends javax.swing.JFrame {

    /**
     * Creates new form Secantes
     */
    public Secantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtX6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtx5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtx4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtx3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtx2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConstante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtib = new javax.swing.JTextField();
        txtxia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtErrorAceptado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDeciamles = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1032, 489));
        setMinimumSize(new java.awt.Dimension(1032, 489));
        setResizable(false);
        setSize(new java.awt.Dimension(1032, 489));
        getContentPane().setLayout(null);

        jLabel1.setText("x⁶");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 13, 19);

        txtX6.setText("");
        getContentPane().add(txtX6);
        txtX6.setBounds(10, 50, 70, 25);

        jLabel2.setText("x⁵");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 20, 13, 19);

        txtx5.setText("");
        getContentPane().add(txtx5);
        txtx5.setBounds(100, 50, 70, 25);

        jLabel3.setText("x⁴");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 20, 13, 19);

        txtx4.setText("");
        getContentPane().add(txtx4);
        txtx4.setBounds(200, 50, 70, 25);

        jLabel4.setText("x³");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 20, 13, 19);

        txtx3.setText("");
        getContentPane().add(txtx3);
        txtx3.setBounds(300, 50, 70, 25);

        jLabel5.setText("x²");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 20, 13, 19);

        txtx2.setText("");
        getContentPane().add(txtx2);
        txtx2.setBounds(400, 50, 70, 25);

        jLabel6.setText("x");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 20, 7, 19);

        txtx.setText("");
        getContentPane().add(txtx);
        txtx.setBounds(500, 50, 70, 25);

        jLabel7.setText("Constante");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(600, 20, 90, 19);

        txtConstante.setText("");
        getContentPane().add(txtConstante);
        txtConstante.setBounds(600, 50, 70, 25);

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String[]{
                        "Iteracion", "Resultado", "Error"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 90, 452, 402);

        jLabel8.setText("Intervalos");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 120, 110, 19);

        jLabel9.setText("xi-1");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 180, 23, 19);

        jLabel10.setText("xi");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 180, 11, 19);
        getContentPane().add(txtib);
        txtib.setBounds(150, 210, 70, 25);
        getContentPane().add(txtxia);
        txtxia.setBounds(10, 210, 70, 25);

        jLabel11.setText("Error Aceptado");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 290, 120, 19);
        getContentPane().add(txtErrorAceptado);
        txtErrorAceptado.setBounds(150, 290, 180, 25);

        jLabel12.setText("Decimales");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 330, 120, 19);
        getContentPane().add(txtDeciamles);
        txtDeciamles.setBounds(150, 330, 180, 25);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(790, 40, 130, 25);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(400, 430, 130, 25);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        //crear variables para los txtfield
        double x6, x5, x4, x3, x2, x, cte, xi, ib, errorAceptado;
        int decimales;
        //validar cada campo de texto con su respectivo metodo
        if (validarTxtField(txtX6) && validarTxtField(txtx5) && validarTxtField(txtx4) && validarTxtField(txtx3) && validarTxtField(txtx2) && validarTxtField(txtx) && validarTxtField(txtConstante) && validarTxtField(txtxia) && validarTxtField(txtib) && validarTxtField(txtErrorAceptado) && validarTxtField(txtDeciamles) && Esint(txtDeciamles)) {
            //asignar el valor de cada txtfield a su respectiva variable
            x6 = Double.parseDouble(txtX6.getText());
            x5 = Double.parseDouble(txtx5.getText());
            x4 = Double.parseDouble(txtx4.getText());
            x3 = Double.parseDouble(txtx3.getText());
            x2 = Double.parseDouble(txtx2.getText());
            x = Double.parseDouble(txtx.getText());
            cte = Double.parseDouble(txtConstante.getText());
            xi = Double.parseDouble(txtxia.getText());
            ib = Double.parseDouble(txtib.getText());
            errorAceptado = Double.parseDouble(txtErrorAceptado.getText());
            decimales = Integer.parseInt(txtDeciamles.getText());
            //crear un objeto de la clase secantes
            Secante secante = new Secante(x6, x5, x4, x3, x2, x, cte, xi, ib, errorAceptado, decimales);
            //crear un objeto de la clase DefaultTableModel
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            //limpiar la tabla
            modelo.setRowCount(0);
            //llamar al metodo calcular de la clase secantes
            secante.calcular(modelo);
        } else {
            //mensaje de error
            javax.swing.JOptionPane.showMessageDialog(this, "Corriga los campos en rojo");
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        //limpia todos los campos y la tabla
        txtX6.setText("");
        txtx5.setText("");
        txtx4.setText("");
        txtx3.setText("");
        txtx2.setText("");
        txtx.setText("");
        txtConstante.setText("");
        txtxia.setText("");
        txtib.setText("");
        txtErrorAceptado.setText("");
        txtDeciamles.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);


    }//GEN-LAST:event_btnLimpiarActionPerformed


    /**
     * Este método se utiliza para validar que el texto obtenido de un JTextField sea un número (entero o decimal).
     * No debe estar vacío y no debe contener letras ni signos (excepto el punto decimal).
     *
     * @param txtField El JTextField que se va a validar.
     * @return true si el texto es un número, false en caso contrario.
     */
    public boolean validarTxtField(javax.swing.JTextField txtField) {
        // Validar que no esté vacío y que sea un número (entero o decimal)
        if (txtField.getText().isEmpty() || !txtField.getText().matches("-?[0-9]+\\.?[0-9]*")) {
            // Pinta el borde de rojo si no es válido
            txtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            return false;
        } else {
            // Pinta el borde de negro si es válido
            txtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            return true;
        }
    }
    /**
     * Este método se utiliza para validar que el texto obtenido de un JTextField sea un entero.
     *
     * @param txtfield El JTextField que se va a validar.
     * @return true si el texto es un entero, false en caso contrario.
     */
    public boolean Esint(javax.swing.JTextField txtfield){
        try {
            Integer.parseInt(txtfield.getText());
            //pinta el borde de negro
            txtfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
            return true;
        } catch (NumberFormatException e) {
            //pinta el borde de rojo
            txtfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
            return false;
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtConstante;
    private javax.swing.JTextField txtDeciamles;
    private javax.swing.JTextField txtErrorAceptado;
    private javax.swing.JTextField txtX6;
    private javax.swing.JTextField txtib;
    private javax.swing.JTextField txtx;
    private javax.swing.JTextField txtx2;
    private javax.swing.JTextField txtx3;
    private javax.swing.JTextField txtx4;
    private javax.swing.JTextField txtx5;
    private javax.swing.JTextField txtxia;
    // End of variables declaration//GEN-END:variables
}
