package metodoResiduos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.table.DefaultTableModel;

/**
 * @author isaac
 */
public class MeodoDeLosResiduos extends javax.swing.JFrame {

    /**
     * Creates new form MeodoDeLosResiduos
     */
    public MeodoDeLosResiduos() {
        initComponents();
    }

    private javax.swing.JTable tableIntervalos;
    private javax.swing.JScrollPane jScrollPane1;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        X6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtx5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtX4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtx3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtX2 = new javax.swing.JTextField();
        x = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDecimales = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnError = new javax.swing.JTextField();
        btnIngresarIntervalos = new javax.swing.JButton();
        btnPorporcionarIntervalos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableResultados = new javax.swing.JTable();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("metodo de los residuos");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1180, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(1180, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("METODO DE LOS RESIDUOS");

        btnCalcular.setBackground(new java.awt.Color(0, 0, 0));
        btnCalcular.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setToolTipText("");
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setMargin(null);

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(btnCalcular)
                .addGap(83, 83, 83)
                .addComponent(btnLimpiar)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 927, 47);

        jLabel1.setText("x⁶");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 13, 18);
        getContentPane().add(X6);
        X6.setBounds(10, 100, 50, 24);

        jLabel2.setText("x⁵");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 70, 13, 18);
        getContentPane().add(txtx5);
        txtx5.setBounds(70, 100, 50, 24);

        jLabel3.setText("x⁴");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 70, 13, 18);
        getContentPane().add(txtX4);
        txtX4.setBounds(130, 100, 50, 24);

        jLabel4.setText("x³");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 70, 12, 18);
        getContentPane().add(txtx3);
        txtx3.setBounds(190, 100, 50, 24);

        jLabel5.setText("x²");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 70, 12, 18);
        getContentPane().add(txtX2);
        txtX2.setBounds(250, 100, 50, 24);

        x.setText("x");
        getContentPane().add(x);
        x.setBounds(330, 70, 7, 18);
        getContentPane().add(txtX);
        txtX.setBounds(310, 100, 50, 24);

        jLabel7.setText("x⁶");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 70, 13, 18);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(10, 100, 50, 24);

        jLabel8.setText("C");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 70, 11, 18);
        getContentPane().add(txtC);
        txtC.setBounds(370, 100, 50, 24);

        jLabel6.setText("Ingresar numero de decimales");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 150, 220, 18);
        getContentPane().add(txtDecimales);
        txtDecimales.setBounds(230, 150, 270, 24);

        jLabel9.setText("Ingresar error relativo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 220, 150, 18);
        getContentPane().add(btnError);
        btnError.setBounds(230, 220, 270, 24);

        btnIngresarIntervalos.setText("Ingresar Intervalos");
        btnIngresarIntervalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarIntervalosActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarIntervalos);
        btnIngresarIntervalos.setBounds(500, 90, 170, 24);

        btnPorporcionarIntervalos.setText("Proporcionar intervalos");
        btnPorporcionarIntervalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorporcionarIntervalosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPorporcionarIntervalos);
        btnPorporcionarIntervalos.setBounds(680, 90, 190, 24);

        tableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "iteracion", "raiz", "error"
            }
        ));
        jScrollPane2.setViewportView(tableResultados);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 130, 340, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarIntervalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarIntervalosActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnIngresarIntervalosActionPerformed

    private void btnPorporcionarIntervalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorporcionarIntervalosActionPerformed
        // TODO add your handling code here:
        tableIntervalos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();

        //btnCalcular queda deshabilitado
        btnCalcular.setEnabled(false);

        DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"", "Intervalos"});





        //se valida que los txtfield sean double
        double x6 = validarTxtField(X6);
        double x5 = validarTxtField(txtx5);
        double x4 = validarTxtField(txtX4);
        double x3 = validarTxtField(txtx3);
        double x2 = validarTxtField(txtX2);
        double x1 = validarTxtField(txtX);
        double x0 = validarTxtField(jTextField7);
        double c = validarTxtField(txtC);

        //se valida que los txtfield sean double
        int decimales = validarTxtFieldINT(txtDecimales);
        double error = validarTxtField(btnError);

        //se crea un objeto de la clase encontrarIntervalos
        encontrarIntervalos intervalos = new encontrarIntervalos(c);

        //se llama al metodo encontrarIntervalos
        double[] intervalosArray = intervalos.encontrarIntervalos();




        for (double intervalo : intervalosArray) {
            model.addRow(new Object[]{null, intervalo});
        }

        tableIntervalos.setModel(model);


        jScrollPane1.setViewportView(tableIntervalos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(980, 20, 160, 180);


    }//GEN-LAST:event_btnPorporcionarIntervalosActionPerformed

    //meotodo que recibe txtfield y valida que se conviertan a double
    public double validarTxtField(javax.swing.JTextField txtField) {
        double valor = 0;
        //si el txtfield esta vacio regresa 0
        if (txtField.getText().isEmpty()) {
            return valor; //regresa 0


        }
        //si el txtfield no esta vacio se convierte a double
        try {
            valor = Double.parseDouble(txtField.getText());
        } catch (NumberFormatException e) {
            //si no se puede convertir en double se pinta de rojo el borde y se lanza un JOpaint
            txtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            javax.swing.JOptionPane.showMessageDialog(null, "Corriga los campos en rojo");


        }
        return valor;
    }

    //metodo que recibe txtfield y valida que sea un entero
    public int validarTxtFieldINT(javax.swing.JTextField txtField) {
        int valor = 0;
        //si el txtfield esta vacio regresa 0
        if (txtField.getText().isEmpty()) {
            return valor; //regresa 0
        }
        //si el txtfield no esta vacio se convierte a int
        try {
            valor = Integer.parseInt(txtField.getText());
        } catch (NumberFormatException e) {
            //si no se puede convertir en int se pinta de rojo el borde y se lanza un JOpaint
            txtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            javax.swing.JOptionPane.showMessageDialog(null, "Corriga los campos en rojo");
        }
        return valor;
    }




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeodoDeLosResiduos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeodoDeLosResiduos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeodoDeLosResiduos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeodoDeLosResiduos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeodoDeLosResiduos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField X6;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JTextField btnError;
    private javax.swing.JButton btnIngresarIntervalos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPorporcionarIntervalos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tableResultados;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtDecimales;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtX4;
    private javax.swing.JTextField txtx3;
    private javax.swing.JTextField txtx5;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
