package metodoResiduos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author isaac
 */
public class MeodoDeLosResiduos extends JFrame {

    /**
     * Creates new form MeodoDeLosResiduos
     */
    public MeodoDeLosResiduos() {
        initComponents();
        tableIntervalos = new JTable();
    }

    private JTable tableIntervalos;
    private JScrollPane jScrollPane1;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        X6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtx5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtX4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtx3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtX2 = new javax.swing.JTextField();
        x = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDecimales = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnError = new javax.swing.JTextField();
        btnPorporcionarIntervalos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableResultados = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtb = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("metodo de los residuos");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1180, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(1180, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("METODO DE LOS RESIDUOS");

        btnCalcular.setBackground(new java.awt.Color(0, 0, 0));
        btnCalcular.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setToolTipText("");
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setMargin(null);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(btnCalcular)
                .addGap(83, 83, 83)
                .addComponent(btnLimpiar)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 916, 49);

        jLabel1.setText("x⁶");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 10, 16);
        getContentPane().add(X6);
        X6.setBounds(10, 100, 50, 22);

        jLabel2.setText("x⁵");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 70, 10, 16);
        getContentPane().add(txtx5);
        txtx5.setBounds(70, 100, 50, 22);

        jLabel3.setText("x⁴");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 70, 10, 16);
        getContentPane().add(txtX4);
        txtX4.setBounds(130, 100, 50, 22);

        jLabel4.setText("x³");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 70, 10, 16);
        getContentPane().add(txtx3);
        txtx3.setBounds(190, 100, 50, 22);

        jLabel5.setText("x²");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 70, 10, 16);
        getContentPane().add(txtX2);
        txtX2.setBounds(250, 100, 50, 22);

        x.setText("x");
        getContentPane().add(x);
        x.setBounds(330, 70, 6, 16);
        getContentPane().add(txtX);
        txtX.setBounds(310, 100, 50, 22);

        jLabel7.setText("x⁶");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 70, 10, 16);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(10, 100, 50, 22);

        jLabel8.setText("C");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 70, 8, 16);
        getContentPane().add(txtC);
        txtC.setBounds(370, 100, 50, 22);

        jLabel6.setText("Ingresar numero de decimales");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 150, 220, 16);
        getContentPane().add(txtDecimales);
        txtDecimales.setBounds(230, 150, 270, 22);

        jLabel9.setText("Ingresar error relativo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 220, 150, 16);
        getContentPane().add(btnError);
        btnError.setBounds(230, 220, 270, 22);

        btnPorporcionarIntervalos.setText("Proporcionar intervalos");
        btnPorporcionarIntervalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorporcionarIntervalosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPorporcionarIntervalos);
        btnPorporcionarIntervalos.setBounds(520, 90, 440, 23);

        tableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "iteracion", "raiz", "error"
            }
        ));
        jScrollPane2.setViewportView(tableResultados);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 130, 440, 320);

        jLabel10.setText("Intervalos:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 280, 70, 16);

        jLabel11.setText("a");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 330, 6, 16);
        getContentPane().add(txta);
        txta.setBounds(20, 360, 64, 22);

        jLabel12.setText("b");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(130, 340, 7, 16);
        getContentPane().add(txtb);
        txtb.setBounds(120, 360, 64, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(ActionEvent evt) {
        // Validar y obtener los coeficientes del polinomio
        double x6 = validarTxtField(X6);
        double x5 = validarTxtField(txtx5);
        double x4 = validarTxtField(txtX4);
        double x3 = validarTxtField(txtx3);
        double x2 = validarTxtField(txtX2);
        double x1 = validarTxtField(txtX);
        double c = validarTxtField(txtC);


        // Crear el polinomio
        Polinomio polinomio = new Polinomio(x6, x5, x4, x3, x2, x1, c);

        // Validar y obtener el número de decimales y el error permitido
        int decimales = validarTxtFieldINT(txtDecimales);
        double errorPermitido = validarTxtField(btnError);

        // Validar y obtener los intervalos
        double a = validarTxtField(txta);
        double b = validarTxtField(txtb);

        // Crear la instancia del método de bisección
        Biseccion biseccion = new Biseccion(polinomio, errorPermitido);

        // Encontrar las raíces
        ArrayList<ResultadoBiseccion> resultados = biseccion.encontrarRaices(a, b);

        // Mostrar los resultados en la tabla
        DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"Iteración", "Aproximación", "Error relativo"});
        for (ResultadoBiseccion resultado : resultados) {
            model.addRow(new Object[]{resultado.iteracion, String.format("%." + decimales + "f", resultado.aproximacion), String.format("%." + decimales + "f", resultado.errorRelativo)});
        }
        tableResultados.setModel(model);



    }

    private void btnPorporcionarIntervalosActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnPorporcionarIntervalosActionPerformed
        // TODO add your handling code here:
        tableIntervalos = new JTable();
        jScrollPane1 = new JScrollPane();

        //btnCalcular queda deshabilitado
        btnCalcular.setEnabled(false);

        DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"", "Intervalos"});


        //se valida que los txtfield sean double
        double x6 = validarTxtField(X6);
        double x5 = validarTxtField(txtx5);
        double x4 = validarTxtField(txtX4);
        double x3 = validarTxtField(txtx3);
        double x2 = validarTxtField(txtX2);
        double x1 = validarTxtField(txtX);
        double x0 = validarTxtField(jTextField7);
        double c = validarTxtField(txtC);


        //se crea un objeto de la clase encontrarIntervalos
        encontrarIntervalos intervalos = new encontrarIntervalos(c);

        //se llama al metodo encontrarIntervalos
        double[] intervalosArray = intervalos.encontrarIntervalos();

        /*
         * Crear en un while un objeto de la clase Residuos que crea dos double que reciben dos intervalos del arreglo de intervalos
         * este while durara mientras que no reciba un false de la clase Residuos
         * */
        boolean exit = true;
        int i = 0;
        ArrayList<String> validacion = new ArrayList<>();


        // El bucle continúa hasta que se procese el último intervalo
        while (i < intervalosArray.length - 1) {
            double a = intervalosArray[i];
            double b = intervalosArray[i+1]; //

            Residuos residuos = new Residuos(x6, x5, x4, x3, x2, x1, c, a, b);

           double fa = residuos.encontrarvalor();
           double fb = residuos.encontrarvalorb();


            System.out.println("Intervalo [" + a + ", " + b + "]: fa = " + fa + ", fb = " + fb);

              // Se verifica si la multiplicación de fa y fb es menor a 0
            if (fa * fb < 0) {
                /*
                 * se crea un arreglo que almacena "es valido" o "no es valido" dependiendo de si la multiplicacion de fa y fb es menor a 0
                 * */
                validacion.add("Es valido");
            } else {
                validacion.add("No es valido");
            }



            // Incrementar i para pasar al siguiente par de intervalos en la próxima iteración
            i++;
        }

        validacion.add(" ");

        // Agregar las filas al modelo de la tabla
        for (int j = 0; j < intervalosArray.length - 1; j++) {
            model.addRow(new Object[]{validacion.get(j), "[" + intervalosArray[j] + ", " + intervalosArray[j + 1] + "]"});
        }

        tableIntervalos.setModel(model);


        jScrollPane1.setViewportView(tableIntervalos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(980, 20, 160, 180);


    }//GEN-LAST:event_btnPorporcionarIntervalosActionPerformed

    //meotodo que recibe txtfield y valida que se conviertan a double
    public double validarTxtField(JTextField txtField) {
        double valor = 0;
        //si el txtfield esta vacio regresa 0
        if (txtField.getText().isEmpty()) {
            return valor; //regresa 0


        }
        //si el txtfield no esta vacio se convierte a double
        try {
            valor = Double.parseDouble(txtField.getText());
        } catch (NumberFormatException e) {
            //si no se puede convertir en double se pinta de rojo el borde y se lanza un JOpaint
            txtField.setBorder(BorderFactory.createLineBorder(new Color(255, 0, 0)));
            JOptionPane.showMessageDialog(null, "Corriga los campos en rojo");


        }
        return valor;
    }

    //metodo que recibe txtfield y valida que sea un entero
    public int validarTxtFieldINT(JTextField txtField) {
        int valor = 0;
        //si el txtfield esta vacio regresa 0
        if (txtField.getText().isEmpty()) {
            return valor; //regresa 0
        }
        //si el txtfield no esta vacio se convierte a int
        try {
            valor = Integer.parseInt(txtField.getText());
        } catch (NumberFormatException e) {
            //si no se puede convertir en int se pinta de rojo el borde y se lanza un JOpaint
            txtField.setBorder(BorderFactory.createLineBorder(new Color(255, 0, 0)));
            JOptionPane.showMessageDialog(null, "Corriga los campos en rojo");
        }
        return valor;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MeodoDeLosResiduos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MeodoDeLosResiduos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MeodoDeLosResiduos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MeodoDeLosResiduos.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeodoDeLosResiduos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField X6;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JTextField btnError;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPorporcionarIntervalos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tableResultados;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtDecimales;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtX4;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txtb;
    private javax.swing.JTextField txtx3;
    private javax.swing.JTextField txtx5;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
