/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReglaFalsaTrigonometrica;

/**
 *
 * @author isaac
 */

import javax.swing.*;

public class ReglaFalsa extends javax.swing.JFrame {

    /**
     * Creates new form ReglaFalsa
     */
    public ReglaFalsa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnx6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnx5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnx4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnx3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnx2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnC = new javax.swing.JTextField();
        RadioRadianes = new javax.swing.JRadioButton();
        RadioGrados = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        radioSeno = new javax.swing.JRadioButton();
        RadioCos = new javax.swing.JRadioButton();
        Radiotan = new javax.swing.JRadioButton();
        radioCot = new javax.swing.JRadioButton();
        radioCsc = new javax.swing.JRadioButton();
        radioSec = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("X⁶");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(51, 17, 15, 19);
        getContentPane().add(btnx6);
        btnx6.setBounds(20, 50, 64, 25);

        jLabel2.setText("x⁵");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 20, 15, 19);
        getContentPane().add(btnx5);
        btnx5.setBounds(100, 50, 64, 25);

        jLabel3.setText("x⁴");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 20, 13, 19);
        getContentPane().add(btnx4);
        btnx4.setBounds(180, 50, 64, 25);

        jLabel4.setText("x³");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 20, 15, 19);
        getContentPane().add(btnx3);
        btnx3.setBounds(260, 50, 64, 25);

        jLabel5.setText("x²");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 20, 13, 19);
        getContentPane().add(btnx2);
        btnx2.setBounds(340, 50, 64, 25);

        jLabel6.setText("x");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 20, 15, 19);
        getContentPane().add(btnx);
        btnx.setBounds(420, 50, 64, 25);

        jLabel7.setText("c");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 20, 15, 19);

        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC);
        btnC.setBounds(500, 50, 64, 25);

        RadioRadianes.setText("Radianes");
        RadioRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioRadianesActionPerformed(evt);
            }
        });
        getContentPane().add(RadioRadianes);
        RadioRadianes.setBounds(40, 220, 83, 23);

        RadioGrados.setText("Grados");
        RadioGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioGradosActionPerformed(evt);
            }
        });
        getContentPane().add(RadioGrados);
        RadioGrados.setBounds(150, 220, 115, 23);

        jLabel15.setText("Error");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 380, 35, 19);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(20, 420, 90, 25);

        jLabel16.setText("Decimales");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(150, 390, 100, 19);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(140, 420, 100, 25);

        radioSeno.setText("Sen");
        getContentPane().add(radioSeno);
        radioSeno.setBounds(60, 130, 47, 23);

        RadioCos.setText("Cos");
        getContentPane().add(RadioCos);
        RadioCos.setBounds(130, 130, 47, 23);

        Radiotan.setText("Tan");
        getContentPane().add(Radiotan);
        Radiotan.setBounds(200, 130, 47, 23);

        radioCot.setText("Cot");
        getContentPane().add(radioCot);
        radioCot.setBounds(270, 130, 47, 23);

        radioCsc.setText("Csc");
        getContentPane().add(radioCsc);
        radioCsc.setBounds(380, 130, 46, 23);

        radioSec.setText("Sec");
        getContentPane().add(radioSec);
        radioSec.setBounds(330, 130, 46, 23);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(630, 50, 100, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Declarar los JRadioButton como variables de instancia
    JRadioButton piRadianButton;
    JRadioButton decimalRadianButton;
    JRadioButton DeciamlesGrado;
    JRadioButton MinutosGrado;


    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void RadioRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioRadianesActionPerformed
        // TODO add your handling code here:
        // Eliminar los botones de grados si existen
        if (DeciamlesGrado != null && MinutosGrado != null) {
            getContentPane().remove(DeciamlesGrado);
            getContentPane().remove(MinutosGrado);
            DeciamlesGrado = null;
            MinutosGrado = null;
        }

        // Crear los nuevos JRadioButton
        piRadianButton = new JRadioButton("PI Radian");
        decimalRadianButton = new JRadioButton("Decimal Radian");

        // Agregar los nuevos botones al panel
        getContentPane().add(piRadianButton);
        getContentPane().add(decimalRadianButton);

        // Posicionar los nuevos botones
        piRadianButton.setBounds(40, 250, 100, 23);
        decimalRadianButton.setBounds(150, 250, 120, 23);

        // Actualizar el panel
        getContentPane().revalidate();
        getContentPane().repaint();

    }//GEN-LAST:event_RadioRadianesActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void RadioGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioGradosActionPerformed
        // TODO add your handling code here:
        //se crean los nuevos JradioButton
        JRadioButton DeciamlesGrado = new JRadioButton("Decimales en grados");
        JRadioButton MinutosGrado = new JRadioButton("DMS");

        //se crea un nuevo ButtonGroup
        ButtonGroup groupUnidadesAngulares = new ButtonGroup();
        groupUnidadesAngulares.add(DeciamlesGrado);
        groupUnidadesAngulares.add(MinutosGrado);

        //se agregan los nuevos JradioButton al panel
        getContentPane().add(DeciamlesGrado);
        getContentPane().add(MinutosGrado);

        //se posicionan los nuevos JradioButton
        DeciamlesGrado.setBounds(40, 250, 150, 23);
        MinutosGrado.setBounds(200, 250, 100, 23);

        //se actualiza el panel
        getContentPane().revalidate();
        getContentPane().repaint();


    }//GEN-LAST:event_RadioGradosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReglaFalsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioCos;
    private javax.swing.JRadioButton RadioGrados;
    private javax.swing.JRadioButton RadioRadianes;
    private javax.swing.JRadioButton Radiotan;
    private javax.swing.JTextField btnC;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JTextField btnx;
    private javax.swing.JTextField btnx2;
    private javax.swing.JTextField btnx3;
    private javax.swing.JTextField btnx4;
    private javax.swing.JTextField btnx5;
    private javax.swing.JTextField btnx6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JRadioButton radioCot;
    private javax.swing.JRadioButton radioCsc;
    private javax.swing.JRadioButton radioSec;
    private javax.swing.JRadioButton radioSeno;
    // End of variables declaration//GEN-END:variables
}
